version: "3.7"
services:
  server:
    container_name: Server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.4.8
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    driver: local